/*
 * Project name:
     Sample.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     2012-09-02
 * Time of creation
     ¿ÀÈÄ 4:33:21
 * Test configuration:
     MCU:             LM3S9B95
     Dev.Board:       mikromedia_for_Stellaris_M3
                      http://www.mikroe.com/eng/products/view/793/mikromedia-for-stellaris-m3/
     Oscillator:      80000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/eng/products/view/752/mikroc-pro-for-arm/
 */

#include "Sample_objects.h"
#include "Sample_resources.h"
#include "Driver.h"
#include "IR.h"

void main() {

  Start_Driver();
  Start_TP();

  TFT_Fill_Screen(0);

  while (1) {

    Check_TP();
    Check_Event();
  }
}
